#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly ENVIRONMENTS_DIR="${REPOSITORY_ROOT}/environments"
readonly DEVCONTAINER_ENV_FILE="${REPOSITORY_ROOT}/docker/.env"

usage() {
    cat <<'USAGE'
Usage: ./scripts/select-env.sh <environment>

Example:
  ./scripts/select-env.sh wp702-default
USAGE
}

fail() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

main() {
    [[ $# -eq 1 ]] || {
        usage >&2
        exit 2
    }

    local environment_name="$1"
    local environment_file="${ENVIRONMENTS_DIR}/${environment_name}.env"
    local temporary_file

    [[ "$environment_name" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ ]] \
        || fail "Invalid environment name: ${environment_name}"
    [[ -f "$environment_file" ]] \
        || fail "Environment definition not found: environments/${environment_name}.env"

    "${SCRIPT_DIR}/env.sh" "$environment_name" config >/dev/null

    temporary_file="$(mktemp "${REPOSITORY_ROOT}/docker/.env.tmp.XXXXXX")"
    trap 'rm -f "${temporary_file:-}"' EXIT

    {
        printf '# Generated by scripts/select-env.sh. Do not edit or commit.\n'
        cat "$environment_file"
    } >"$temporary_file"

    mv "$temporary_file" "$DEVCONTAINER_ENV_FILE"
    trap - EXIT

    printf 'Selected Dev Container environment: %s\n' "$environment_name"
    printf 'Compose project: %s\n' "$(sed -n 's/^COMPOSE_PROJECT_NAME=//p' "$environment_file" | tail -n 1)"
    printf 'Site URL: %s\n' "$(sed -n 's/^WORDPRESS_SITE_URL=//p' "$environment_file" | tail -n 1)"
    printf '\nRun “Dev Containers: Reopen in Container” in VS Code.\n'
}

main "$@"
